[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
